### ISSUE TITLE
The addresses of the students are not properly shown and modified

### ISSUE THREAD

**Issue by htmfilho** [uclouvain/osis-internship#25]
The addresses of the students (the legal and the customizable one) are not properly shown in the interface. When trying to change the address, the modifications are not taken into account.

**Comment by mathieuzen** [comment]
Not able to track down how the model is saved. I'm able to display the information now but when I try to edit information and submit the form, the page is correctly redirected but the information is not modified.

**Comment by mathieuzen** [comment]
Ok i found the errors were due to a combination of: 
- more fields than necessary specified in StudentInformationForm
- typo when interpolating variables in template ("{{ ... }}")
- type email does not accept default value "-" 
All these were preventing the form.isValid() to return True

Maybe it would be preferable to inform the user that the form is not valid and let him correct before redirecting to the student information page.
